services:
  - type: web
    name: stage-backend
    runtime: docker
    repo: https://github.com/senadalmeidapro/stage
    branch: main
    plan: free
    autoDeploy: true

    buildCommand: "./build.sh"

    envVars:
      - key: DJANGO_SECRET_KEY
        value: "U2-1LZ7_moM9vcbJsrfLUPpfx0UlKY9ZV-oK5_1wFcvcFPnWqfa4-cEgOL9_-YoA_R0O1KC906XGMDwaUxmmMUewz613a9eOoQI3rFSf9UpLrqrDdCWWjbAg1eto7HY5nRrM3A"

      - key: DATABASE_URL
        fromDatabase:
          name: stage-db
          property: connectionString

      - key: PORT
        value: "8000"

databases:
  - name: stage-db
    plan: free
