# Generated by Django 5.2 on 2025-06-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseries', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursery',
            name='manager',
            field=models.OneToOneField(help_text="Manager (UserType avec le rôle 'nursery_manager')", limit_choices_to={'type': 'nursery_manager'}, on_delete=django.db.models.deletion.CASCADE, to='users.usertype'),
        ),
    ]
