# Generated by Django 5.2 on 2025-06-23 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseries', '0003_alter_openinghour_close_time_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursery',
            name='manager',
            field=models.OneToOneField(help_text="Manager (UserType avec le rôle 'nursery_manager')", on_delete=django.db.models.deletion.CASCADE, to='users.usertype'),
        ),
    ]
