# Generated by Django 5.2 on 2025-06-11 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='Nom de famille', max_length=100)),
                ('first_name', models.CharField(help_text='Prénom', max_length=100)),
                ('birthday', models.DateField(blank=True, help_text='Date de naissance', null=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True, help_text="Date d'enregistrement")),
                ('detail', models.TextField(blank=True, max_length=500, null=True)),
                ('existe', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(help_text='Utilisateur (type parent) responsable de cet enfant', limit_choices_to={'type': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.usertype')),
            ],
            options={
                'verbose_name': 'Enfant',
                'verbose_name_plural': 'Enfants',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
