# Generated by Django 5.2 on 2025-06-11 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('classrooms', '0001_initial'),
        ('nurseries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du plan (ex. Basic, Premium)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du plan', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text="Prix de l'abonnement", max_digits=10)),
                ('type', models.CharField(choices=[('day', 'Journalier'), ('week', 'Hebdomadaire'), ('month', 'Mensuel'), ('quarter', 'Trimestriel'), ('semester', 'Semestriel'), ('year', 'Annuel')], help_text='Durée du plan', max_length=20)),
                ('valide', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('nursery', models.ForeignKey(help_text='Crèche proposant ce plan', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='nurseries.nursery')),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['nursery', 'type'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Date de début de validité')),
                ('end_date', models.DateField(help_text='Date de fin de validité')),
                ('price', models.DecimalField(decimal_places=2, help_text='Montant payé', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Souscription active ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('plan', models.ForeignKey(help_text='Plan associé à cette souscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'Souscription',
                'verbose_name_plural': 'Souscriptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(help_text='Enfant concerné par cette souscription', on_delete=django.db.models.deletion.CASCADE, related_name='Enfant', to='children.child')),
                ('classroom', models.ForeignKey(help_text='Classe associée à cette souscription', on_delete=django.db.models.deletion.CASCADE, related_name='Class', to='classrooms.classroom')),
                ('group', models.ForeignKey(help_text='Groupe associé à cette souscription', on_delete=django.db.models.deletion.CASCADE, related_name='Group', to='classrooms.group')),
                ('subscription', models.ForeignKey(help_text='Souscription associée', on_delete=django.db.models.deletion.CASCADE, related_name='Abonement', to='subscriptions.subscription')),
            ],
        ),
    ]
