# Generated by Django 5.2 on 2025-06-11 12:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('classrooms', '0002_initial'),
        ('subscriptions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['nursery', 'duration'], 'verbose_name': "Plan d'abonnement", 'verbose_name_plural': "Plans d'abonnement"},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='type',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='valide',
        ),
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('none', ''), ('day', 'Journalier'), ('week', 'Hebdomadaire'), ('month', 'Mensuel'), ('quarter', 'Trimestriel'), ('semester', 'Semestriel'), ('year', 'Annuel')], default='none', help_text='Durée de validité du plan', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Plan actif ?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date de dernière modification'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='parent',
            field=models.ForeignKey( help_text='Parent ayant souscrit à ce plan', limit_choices_to='parent', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.usertype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text="Prix du plan d'abonnement", max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(help_text='Date de fin de la souscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(help_text='Date de début de la souscription'),
        ),
        migrations.CreateModel(
            name='SubscriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Dernière modification')),
                ('child', models.ForeignKey(help_text='Enfant inscrit dans la souscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_details', to='children.child')),
                ('classroom', models.ForeignKey(help_text='Classe assignée à l’enfant', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_details', to='classrooms.classroom')),
                ('group', models.ForeignKey(help_text='Groupe assigné à l’enfant', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_details', to='classrooms.group')),
                ('subscription', models.ForeignKey(help_text='Souscription associée', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Détail de souscription',
                'verbose_name_plural': 'Détails de souscription',
                'ordering': ['child__last_name'],
                'unique_together': {('subscription', 'child')},
            },
        ),
        migrations.DeleteModel(
            name='SubscriptionDetails',
        ),
    ]
