# Generated by Django 5.2 on 2025-06-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('classrooms', '0002_initial'),
        ('nurseries', '0001_initial'),
        ('subscriptions', '0002_alter_plan_options_remove_plan_type_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('none', ''), ('day', 'Journalier'), ('week', 'Hebdomadaire'), ('month', 'Mensuel'), ('quarter', 'Trimestriel'), ('semester', 'Semestriel'), ('year', 'Annuel')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nursery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='nurseries.nursery'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='parent',
            field=models.ForeignKey(limit_choices_to={'type': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.usertype'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondetail',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_details_for_child', to='children.child'),
        ),
        migrations.AlterField(
            model_name='subscriptiondetail',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_details_for_classroom', to='classrooms.classroom'),
        ),
        migrations.AlterField(
            model_name='subscriptiondetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondetail',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_details_for_group', to='classrooms.group'),
        ),
        migrations.AlterField(
            model_name='subscriptiondetail',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='subscriptions.subscription'),
        ),
        migrations.AlterField(
            model_name='subscriptiondetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
