# Generated by Django 5.2 on 2025-06-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscriptiondetail_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date de fin de la souscription (optionnelle, pour les plans à durée limitée)', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(help_text='Date de début de la souscription (obligatoire pour tous les plans)'),
        ),
    ]
