# Generated by Django 5.2 on 2025-06-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix de la souscription (sera calculé automatiquement en fonction du plan)', max_digits=10),
        ),
    ]
