# Generated by Django 5.2 on 2025-06-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetail',
            name='is_valide',
            field=models.BooleanField(default=True, help_text='Indique si le détail de souscription est valide'),
        ),
    ]
