# Generated by Django 5.2 on 2025-06-11 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, help_text='Numéro de téléphone', max_length=15, null=True)),
                ('address', models.TextField(blank=True, help_text='Adresse postale', null=True)),
                ('birthday', models.DateField(blank=True, help_text='Date de naissance', null=True)),
                ('type', models.CharField(choices=[('parent', 'Parent'), ('nursery_assistant', 'Nursery Assistant'), ('nursery_manager', 'Nursery Manager'), ('admin', 'Admin')], default='parent', help_text="Rôle de l'utilisateur (parent, assistant, manager, admin)", max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisateur étendu',
                'verbose_name_plural': 'Utilisateurs étendus',
            },
        ),
    ]
