# Generated by Django 5.2 on 2025-06-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la salle/Classe', max_length=100)),
                ('capacity', models.PositiveIntegerField(help_text='Capacité totale')),
                ('age_range_start', models.PositiveIntegerField(help_text='Âge minimum (en mois)')),
                ('age_range_end', models.PositiveIntegerField(help_text='Âge maximum (en mois)')),
                ('nbr_children', models.PositiveIntegerField(default=0, help_text="Nombre d'enfants dans la salle")),
                ('existe', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Salle / Classe',
                'verbose_name_plural': 'Salles / Classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du groupe', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['name'],
            },
        ),
    ]
