# Generated by Django 5.2 on 2025-06-11 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('nurseries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='nursery',
            field=models.ForeignKey(help_text='Crèche propriétaire de cette salle', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='nurseries.nursery'),
        ),
        migrations.AddField(
            model_name='group',
            name='classroom',
            field=models.ForeignKey(help_text='Classe à laquelle appartient ce groupe', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='classrooms.classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'nursery')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'classroom')},
        ),
    ]
