# Generated by Django 5.2 on 2025-06-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'activité", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description détaillée', null=True)),
                ('type', models.CharField(choices=[('educational', 'Educationnele'), ('recreational', 'Récréationnele'), ('cultural', 'Culturel'), ('other', 'Autre')], help_text="Catégorie de l'activité", max_length=50)),
                ('valide', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateField(help_text="Date de l'activité pour cette classe")),
                ('start_time', models.TimeField(help_text='Heure de début pour la classe')),
                ('end_time', models.TimeField(help_text='Heure de fin pour la classe')),
            ],
            options={
                'verbose_name': 'Activité de classe',
                'verbose_name_plural': 'Activités de classe',
                'ordering': ['start_time'],
            },
        ),
    ]
