# Generated by Django 5.2 on 2025-06-11 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('classrooms', '0001_initial'),
        ('nurseries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='nursery',
            field=models.ForeignKey(help_text='Crèche qui propose cette activité', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='nurseries.nursery'),
        ),
        migrations.AddField(
            model_name='classroomactivity',
            name='activity',
            field=models.ForeignKey(help_text='Activité planifiée', on_delete=django.db.models.deletion.CASCADE, related_name='classroom_links', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='classroomactivity',
            name='classroom',
            field=models.ForeignKey(help_text='Classe réalisant cette activité', on_delete=django.db.models.deletion.CASCADE, related_name='classroom_activities', to='classrooms.classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomactivity',
            unique_together={('classroom', 'activity')},
        ),
    ]
